// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TelmaBolossite;

#nullable disable

namespace TelmaBolossite.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20231108114058_segundamigration")]
    partial class segundamigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("TelmaBolossite.Entidades.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("emailcliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("nomecliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("senhacliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("telefonecliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CLIENTES");
                });

            modelBuilder.Entity("TelmaBolossite.Entidades.Encomenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("dataencomenda")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("dataretirada")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("ENCOMENDA");
                });

            modelBuilder.Entity("TelmaBolossite.Entidades.Encomenda", b =>
                {
                    b.HasOne("TelmaBolossite.Entidades.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });
#pragma warning restore 612, 618
        }
    }
}
