// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TelmaBolossite;

#nullable disable

namespace TelmaBolossite.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20231108113642_inicial")]
    partial class inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("TelmaBolossite.Entidades.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("emailcliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("nomecliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("senhacliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("telefonecliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CLIENTES");
                });
#pragma warning restore 612, 618
        }
    }
}
